import Head from 'next/head'
import HomeTop from '@/components/\bhome/HomeTop'
import Nav from '@/components/layout/Nav'
import Bottom from '@/components/layout/Bottom'
import HomeMiddle from '@/components/\bhome/HomeMiddle'
import HomeBottom from '@/components/\bhome/HomeBottom'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeTop/>
        <HomeMiddle/>
        <HomeBottom/>
      </main>
    </>
  )
}
