import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import HomeTop from '@/components/\bhome/HomeTop'
import Nav from '@/components/layout/Nav'
import Bottom from '@/components/layout/Bottom'
import HomeMiddle from '@/components/\bhome/HomeMiddle'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav/>
        <HomeTop/>
        <HomeMiddle/>
        <Bottom/>
      </main>
    </>
  )
}
